image: node:9.10

cache:
  paths:
    - node_modules

before_script:
  - yarn install

pages:
  stage: deploy
  script:
    - yarn run build:example
    - mkdir -p public
    - cp -r dist/example dist/index.html public/
  artifacts:
    paths:
      - public
  only:
    - master
